# Generated by Django 5.2.4 on 2025-07-17 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MEVTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(max_length=100, unique=True)),
                ('wallet', models.CharField(max_length=100)),
                ('path', models.TextField()),
                ('platforms', models.TextField()),
                ('profit', models.FloatField()),
                ('is_mev', models.BooleanField()),
                ('pattern', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
